name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application
      uses: action-python/pyinstaller-py3.8@amd64
      with:
        path: linkingserver

    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: linkingserver/dist/linux/amd64/server
        target: server

    - uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: linkingserver-linux
        path: |
          server
          config.yml

  build-windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application
      uses: action-python/pyinstaller-py3.8@win64
      with:
        path: linkingserver

    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: linkingserver/dist/windows/win64/server.exe
        target: server.exe

    - uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: linkingserver-windows
        path: |
          server.exe
          config.yml
