name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: linkingserver
        
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: linkingserver/dist/linux/server
        target: server

    - uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: linkingserver-linux
        path: |
          server
          config.yml
        
  build-windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: linkingserver
        
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: linkingserver/dist/windows/server.exe
        target: server.exe

    - uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: linkingserver-windows
        path: |
          server.exe
          config.yml
