name: Package Application with Pyinstaller

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.13'
        spec: 'linkingserver/server.spec'
        requirements: 'linkingserver/requirements.txt'
        
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: dist/server
        target: server

    - uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: linkingserver-linux
        path: |
          server
          config.yml
        
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.13'
        spec: 'linkingserver/server.spec'
        requirements: 'linkingserver/requirements.txt'
        
    - name: copy file
      uses: Lyoko-Jeremie/js-copy-github-action@master
      with:
        source: dist/server.exe
        target: server.exe
        
    - uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: linkingserver-windows
        path: |
          server.exe
          config.yml
